
export const staff = [
  {
    id: 1,
    empName: "Sarah Johnson",
    empEmail: "sarah@glamourstudios.com",
    phone: "+91 98765 43210",
    active: true,
    services: ["Haircut", "Hair Coloring", "Manicure"],
    bookings: "2",
  },
  {
    id: 2,
    empName: "Mike Davis",
    empEmail: "mike@glamourstudios.com",
    phone: "+91 91234 56789",
    active: true,
    services: ["Haircut", "Pedicure"],
    bookings: "8",
  },
  {
    id: 3,
    empName: "Emily Chen",
    empEmail: "emily@glamourstudios.com",
    phone: "+91 99887 77665",
    active: false,
    services: ["Manicure", "Pedicure", "Facial"],
    bookings: "4",
  },
   {
    id: 1,
    empName: "Sarah Johnson",
    empEmail: "sarah@glamourstudios.com",
    phone: "+91 98765 43210",
    active: true,
    services: ["Haircut", "Hair Coloring", "Manicure"],
    bookings: "2",
  },
  {
    id: 2,
    empName: "Mike Davis",
    empEmail: "mike@glamourstudios.com",
    phone: "+91 91234 56789",
    active: true,
    services: ["Haircut", "Pedicure"],
    bookings: "8",
  },
  {
    id: 3,
    empName: "Emily Chen",
    empEmail: "emily@glamourstudios.com",
    phone: "+91 99887 77665",
    active: false,
    services: ["Manicure", "Pedicure", "Facial"],
    bookings: "4",
  },
  
];
